[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables for Netlify Functions
# Set HUGGINGFACE_API_KEY in Netlify dashboard under Site settings > Environment variables